version: '3.8'

services:
  agent:
    build: .
    container_name: securemail_agent_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "50051:50051"
    volumes:
      - ./app:/code/app
