# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secure_mail.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'secure_mail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11secure_mail.proto\"!\n\x0bScanRequest\x12\x12\n\nemail_json\x18\x01 \x01(\t\"l\n\x0cScanResponse\x12\r\n\x05Title\x18\x01 \x01(\t\x12\x0f\n\x07verdict\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x16\n\x0eRecommendation\x18\x05 \x01(\t26\n\nEmailGuard\x12(\n\tScanEmail\x12\x0c.ScanRequest\x1a\r.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secure_mail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCANREQUEST']._serialized_start=21
  _globals['_SCANREQUEST']._serialized_end=54
  _globals['_SCANRESPONSE']._serialized_start=56
  _globals['_SCANRESPONSE']._serialized_end=164
  _globals['_EMAILGUARD']._serialized_start=166
  _globals['_EMAILGUARD']._serialized_end=220
# @@protoc_insertion_point(module_scope)
