# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: secure_mail.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'secure_mail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11secure_mail.proto\x12\x07\x61iagent\";\n\x07RuleHit\x12\x0c\n\x04rule\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x9b\x03\n\x14\x45mailAnalysisRequest\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x11\n\tfrom_addr\x18\x03 \x01(\t\x12\x11\n\tfrom_name\x18\x04 \x01(\t\x12\x11\n\tbody_text\x18\x05 \x01(\t\x12\x12\n\nspam_score\x18\x06 \x01(\x02\x12\x16\n\x0ephishing_score\x18\x07 \x01(\x02\x12\x0f\n\x07is_spam\x18\x08 \x01(\x08\x12\x13\n\x0bis_phishing\x18\t \x01(\x08\x12#\n\trule_hits\x18\n \x03(\x0b\x32\x10.aiagent.RuleHit\x12\x16\n\x0ehas_attachment\x18\x0b \x01(\x08\x12\x17\n\x0fmalware_verdict\x18\x0c \x01(\t\x12\x15\n\rmalware_score\x18\r \x01(\x02\x12\x18\n\x10malware_severity\x18\x0e \x01(\t\x12\x12\n\nmailbox_id\x18\x0f \x01(\x05\x12\x1c\n\x14previous_email_count\x18\x10 \x01(\x05\x12\x1c\n\x14sender_typical_topic\x18\x11 \x01(\t\"\xc9\x02\n\x0e\x41nalysisReport\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x0f\n\x07verdict\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x13\n\x0b\x65xplanation\x18\x05 \x01(\t\x12\x0f\n\x07summary\x18\x06 \x01(\t\x12\x19\n\x11reply_suggestions\x18\x07 \x03(\t\x12\x13\n\x0bis_campaign\x18\x08 \x01(\x08\x12\x1c\n\x14\x63\x61mpaign_description\x18\t \x01(\t\x12\x10\n\x08priority\x18\n \x01(\t\x12\x17\n\x0fpriority_reason\x18\x0b \x01(\t\x12\x1a\n\x12\x62\x65havioral_anomaly\x18\x0c \x01(\x08\x12\x1b\n\x13\x61nomaly_description\x18\r \x01(\t\x12\x16\n\x0erecommendation\x18\x0e \x01(\t2Z\n\x0e\x41IAgentService\x12H\n\x0eGenerateReport\x12\x1d.aiagent.EmailAnalysisRequest\x1a\x17.aiagent.AnalysisReportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secure_mail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RULEHIT']._serialized_start=30
  _globals['_RULEHIT']._serialized_end=89
  _globals['_EMAILANALYSISREQUEST']._serialized_start=92
  _globals['_EMAILANALYSISREQUEST']._serialized_end=503
  _globals['_ANALYSISREPORT']._serialized_start=506
  _globals['_ANALYSISREPORT']._serialized_end=835
  _globals['_AIAGENTSERVICE']._serialized_start=837
  _globals['_AIAGENTSERVICE']._serialized_end=927
# @@protoc_insertion_point(module_scope)
